annotation_route:
    resource: "@AppBundle/Controller/"
    type:     annotation

yaml_route:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /member
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin:
    path: /admin
    defaults: { _controller: "AppBundle:Admin:index" }
