# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
            in_memory:
                memory:
                    users:
                        casperice:
                            password: $2y$12$rEZtKha2WZyBx.ChWlWxk.GkLsBTh4QCcQIOu1kXcHs7xpvvi9JXq
                            roles: 'ROLE_ADMIN'
                        casper:
                            password: $2y$12$rEZtKha2WZyBx.ChWlWxk.GkLsBTh4QCcQIOu1kXcHs7xpvvi9JXq
                            roles: 'ROLE_USER'
           # fos_userbundle:
              #  id: fos_user.user_provider.username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        #FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~



            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        secured_area:
            pattern: ^/logout
            http_basic: ~
            logout:
                path: /logout
                target: /address

        #main:
         #   pattern: ^/
          #  form_login:
           #     provider: fos_userbundle
            #    csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_USER]  }

